# Generated by Django 5.1 on 2024-09-19 07:40

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagory_Name', models.CharField(max_length=150)),
                ('Catagory_Image', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('Catagory_Description', models.TextField(max_length=200)),
                ('Status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=150)),
                ('Product_Vender', models.CharField(max_length=150)),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('Quantity', models.IntegerField()),
                ('Original_price', models.FloatField()),
                ('Selling_price', models.FloatField()),
                ('Product_Description', models.TextField(max_length=200)),
                ('Status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('Trending_product', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('product_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
            ],
        ),
    ]
